version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
